blank_issues_enabled: false
contact_links:
  - name: â“ question - GitHub Discussions
    url: https://github.com/TouK/nussknacker/discussions/categories/q-a
    about: Use GitHub Discussions for unanswered questions only, requiring a maintainer's answer. Make sure the question wasn't already asked.
