version: '3.7'

services:
  app:
    container_name: nussknacker_app
    image: ${NUSSKNACKER_IMAGE-touk/nussknacker}:${NUSSKNACKER_VERSION-latest}
    ports:
      - "3081:8080"
    environment:
      NUSSKNACKER_CONFIG_FILE: ${NUSSKNACKER_CONFIG_FILE:-/opt/nussknacker/conf/docker-application.conf}
      JDK_JAVA_OPTIONS: -Xmx256M
    volumes:
      - ./nk/conf/application.conf:/opt/nussknacker/conf/application.conf
      - nussknacker_storage_app:/opt/nussknacker/storage

volumes:
  nussknacker_storage_app:
