version: '3.7'

services:
  app:
    container_name: nussknacker_app
    image: ${NUSSKNACKER_IMAGE-touk/nussknacker}:${NUSSKNACKER_VERSION-latest}
    ports:
      - "3081:8080"
    environment:
      #multiple, comma separated, config files can be used. They will be merged in order, via HOCON fallback mechanism
      #https://github.com/lightbend/config/blob/master/HOCON.md#config-object-merging-and-file-merging
      NUSSKNACKER_CONFIG_FILE: ${NUSSKNACKER_CONFIG_FILE-/opt/nussknacker/conf/application.conf,/opt/nussknacker/conf/nussknacker.conf}
      JDK_JAVA_OPTIONS: -Xmx256M
      FLINK_ROCKSDB_CHECKPOINT_DATA_URI: s3://flink/rocksdb-checkpoints
    volumes:
      - nussknacker_storage_app:/opt/nussknacker/storage
      - ./nussknacker/nussknacker.conf:/opt/nussknacker/conf/nussknacker.conf

volumes:
  nussknacker_storage_app:
