server.name: kibana
server.host: "0"
server.basePath: /kibana
server.rewriteBasePath: false

elasticsearch.hosts: http://elasticsearch:9200

xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false