name: Gitbook publish

on:
  pull_request:
    branches:
      - master
      - staging
#  push:
#    branches: [ master ]

defaults:
  run:
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install gitbook and build docs
        run: |
          npm install gitbook-cli
          node_modules/gitbook-cli/bin/gitbook.js build
#      - name: Deploy to GithubPages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./docs/_book
#          commit_message: "Updating docs on push to master"